"""
Paper Trading Engine
====================
Real-time paper trading system that:
- Generates live signals from all 6 Phase 3 models
- Executes orders with realistic simulation
- Tracks P&L and performance metrics
- Manages risk with circuit breakers and position limits
- Integrates Phase 6 health and performance monitoring

Architecture:
  Signal Generation (6 models) → Order Creation → Execution Simulation → 
  Position Tracking → P&L Calculation → Risk Management → Monitoring
"""

import uuid
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
import asyncio
import numpy as np
from loguru import logger

# Phase 5 backtester infrastructure
from src.backtesting.execution import ExecutionSimulator, ExecutionConfig, SlippageModel
from src.backtesting.portfolio import PortfolioTracker

# Phase 6 monitoring
try:
    from src.infrastructure.health_monitor import HealthMonitor
    from src.models.performance_monitor import ModelPerformanceMonitor
except ImportError:
    HealthMonitor = None
    ModelPerformanceMonitor = None

from src.utils.config import get_config


class SignalType(Enum):
    """Trading signal types."""
    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE = "CLOSE"
    HOLD = "HOLD"


class TradeStatus(Enum):
    """Trade status tracking."""
    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"


@dataclass
class ModelSignal:
    """Signal generated by a model."""
    model_name: str  # 'wavelet', 'hmm', 'lstm', 'tft', 'genetic', 'ensemble'
    signal_type: SignalType
    confidence: float  # 0-1
    entry_price: float
    current_price: float
    timestamp: datetime
    reasoning: str = ""
    regime: str = "NORMAL"  # Market regime


@dataclass
class TradeExecution:
    """Executed trade record."""
    trade_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: datetime = field(default_factory=datetime.now)
    model_name: str = ""
    signal_type: SignalType = SignalType.HOLD
    entry_price: float = 0.0
    entry_time: datetime = field(default_factory=datetime.now)
    exit_price: Optional[float] = None
    exit_time: Optional[datetime] = None
    quantity: float = 0.0  # Ounces of gold
    position_value: float = 0.0
    pnl: float = 0.0  # P&L in dollars
    pnl_pct: float = 0.0  # P&L percentage
    commission: float = 0.0
    slippage: float = 0.0
    status: TradeStatus = TradeStatus.PENDING
    regime: str = "NORMAL"
    confidence: float = 0.0
    
    def __repr__(self):
        return f"Trade({self.trade_id}) {self.model_name} {self.signal_type.value} @ {self.entry_price:.2f}"


@dataclass
class PortfolioSnapshot:
    """Point-in-time portfolio state."""
    timestamp: datetime
    total_value: float
    cash: float
    position_quantity: float  # Gold quantity in ounces
    position_value: float  # Mark-to-market value
    pnl_realized: float  # Closed trades P&L
    pnl_unrealized: float  # Open position P&L
    pnl_total: float  # Total P&L
    daily_pnl: float
    return_pct: float  # Return as percentage
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    num_trades: int = 0


@dataclass
class PaperTradingConfig:
    """Configuration for paper trading."""
    initial_capital: float = 100000.0      # Starting capital ($)
    symbol: str = "XAUUSD"                 # Trading instrument
    
    # Position sizing
    kelly_fraction: float = 0.25           # Kelly criterion fraction
    max_position_pct: float = 0.10         # Max position as % of capital
    max_daily_loss_pct: float = 0.02       # Max daily loss % (circuit breaker)
    max_drawdown_pct: float = 0.15         # Max drawdown % (stop all trading)
    
    # Execution
    commission_per_trade: float = 5.0
    commission_pct: float = 0.0001
    slippage_model: str = "spread"         # 'fixed', 'spread', 'impact'
    slippage_pct: float = 0.01             # Typical bid-ask spread for gold (1 bps)
    
    # Signal configuration
    min_confidence: float = 0.6            # Min confidence to trade
    signal_weights: Dict[str, float] = field(default_factory=lambda: {
        "wavelet": 0.15,
        "hmm": 0.15,
        "lstm": 0.20,
        "tft": 0.20,
        "genetic": 0.15,
        "ensemble": 0.15,
    })
    
    # Trading hours
    trading_enabled: bool = True
    trading_start_hour: int = 0            # 00:00 UTC
    trading_end_hour: int = 23             # 23:59 UTC


class PaperTradingEngine:
    """
    Core paper trading engine.
    
    Orchestrates:
    1. Signal generation from all 6 models
    2. Position sizing and risk checks
    3. Order execution simulation
    4. P&L tracking and monitoring
    5. Risk management enforcement
    """
    
    def __init__(self, config: Optional[PaperTradingConfig] = None):
        """Initialize paper trading engine."""
        self.config = config or PaperTradingConfig()
        self.state_config = get_config()
        
        # Core state
        self.status = "INITIALIZED"
        self.started_at: Optional[datetime] = None
        self.stopped_at: Optional[datetime] = None
        
        # Portfolio tracking
        self.portfolio = PortfolioTracker(self.config.initial_capital)
        # Simple position size tracking (separate from PortfolioTracker's open_positions)
        self.position_sizes: Dict[str, float] = {}
        self.execution_sim = ExecutionSimulator(ExecutionConfig(
            commission_per_trade=self.config.commission_per_trade,
            commission_pct=self.config.commission_pct,
            slippage_model=SlippageModel(self.config.slippage_model),
            slippage_pct=self.config.slippage_pct,
        ))
        
        # Trade history
        self.trades: List[TradeExecution] = []
        self.current_position: Optional[TradeExecution] = None
        self.portfolio_snapshots: List[PortfolioSnapshot] = []
        
        # Daily tracking
        self.day_started_at: Optional[datetime] = None
        self.daily_pnl: float = 0.0
        self.daily_trades: List[TradeExecution] = []
        
        # Model signals
        self.last_signals: Dict[str, ModelSignal] = {}
        self.signal_history: Dict[str, List[ModelSignal]] = {
            model: [] for model in ["wavelet", "hmm", "lstm", "tft", "genetic", "ensemble"]
        }
        
        # Monitoring (Phase 6)
        self.health_monitor: Optional[HealthMonitor] = None
        self.performance_monitor: Optional[ModelPerformanceMonitor] = None
        
        logger.info(f"Paper Trading Engine initialized with ${self.config.initial_capital:,.0f} capital")
    
    def start(self) -> Dict:
        """Start paper trading."""
        if self.status == "RUNNING":
            logger.warning("Paper trading already running")
            return {"status": "RUNNING", "message": "Already started"}
        
        self.status = "RUNNING"
        self.started_at = datetime.now()
        self.day_started_at = datetime.now()
        self.daily_pnl = 0.0
        
        logger.info("Paper trading started")
        return {
            "status": "RUNNING",
            "started_at": self.started_at.isoformat(),
            "initial_capital": self.config.initial_capital,
            "current_value": self._create_portfolio_snapshot().total_value,
        }
    
    def stop(self) -> Dict:
        """Stop paper trading and close all positions."""
        if self.status != "RUNNING":
            return {"status": self.status, "message": "Not running"}
        
        # Close current position if open
        if self.current_position and self.current_position.status == TradeStatus.OPEN:
            exit_price = self.current_position.entry_price
            for sig in self.last_signals.values():
                if sig.current_price > 0:
                    exit_price = sig.current_price
                    break
            self._close_position(datetime.now(), exit_price)
        
        self.status = "STOPPED"
        self.stopped_at = datetime.now()
        
        logger.info(f"Paper trading stopped. Final P&L: ${self.get_total_pnl():.2f}")
        return {
            "status": "STOPPED",
            "stopped_at": self.stopped_at.isoformat(),
            "final_value": self._create_portfolio_snapshot().total_value,
            "total_pnl": self.get_total_pnl(),
            "total_trades": len(self.trades),
        }
    
    def get_status(self) -> Dict:
        """Get current engine status."""
        snapshot = self._create_portfolio_snapshot()
        return {
            "status": self.status,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "current_time": datetime.now().isoformat(),
            "portfolio": {
                "total_value": snapshot.total_value,
                "cash": snapshot.cash,
                "position_quantity": snapshot.position_quantity,
                "position_value": snapshot.position_value,
                "pnl_total": snapshot.pnl_total,
                "pnl_daily": snapshot.daily_pnl,
                "return_pct": snapshot.return_pct,
            },
            "trading": {
                "num_trades": len(self.trades),
                "daily_trades": len(self.daily_trades),
                "win_rate": self._calculate_win_rate(),
                "position_status": "OPEN" if self.current_position else "FLAT",
            },
            "models": {
                model: {
                    "last_signal": self.last_signals[model].signal_type.value if model in self.last_signals else None,
                    "confidence": self.last_signals[model].confidence if model in self.last_signals else 0.0,
                    "signal_count": len(self.signal_history[model]),
                } for model in self.config.signal_weights.keys()
            }
        }
    
    def process_signal(self, model_name: str, signal: ModelSignal) -> Optional[TradeExecution]:
        """
        Process a new signal from a model.
        
        Args:
            model_name: Name of the model generating the signal
            signal: ModelSignal with entry price and confidence
            
        Returns:
            TradeExecution if trade was executed, None otherwise
        """
        if self.status != "RUNNING":
            return None
        
        # Store signal
        self.last_signals[model_name] = signal
        self.signal_history[model_name].append(signal)
        
        # Check confidence threshold
        if signal.confidence < self.config.min_confidence:
            logger.debug(f"{model_name} signal below confidence threshold: {signal.confidence}")
            return None
        
        # Check risk limits
        if not self._check_risk_limits():
            logger.warning("Risk limits exceeded, skipping trade")
            return None
        
        # Check if position already open
        if self.current_position and self.current_position.status == TradeStatus.OPEN:
            # If signal is CLOSE or opposite direction, close existing position
            if signal.signal_type == SignalType.CLOSE or \
               (self.current_position.signal_type == SignalType.LONG and signal.signal_type == SignalType.SHORT) or \
               (self.current_position.signal_type == SignalType.SHORT and signal.signal_type == SignalType.LONG):
                self._close_position(signal.timestamp, signal.current_price)
            else:
                logger.debug("Position already open, skipping new signal")
                return None
        
        # Execute trade
        if signal.signal_type in (SignalType.LONG, SignalType.SHORT):
            return self._execute_trade(model_name, signal)
        elif signal.signal_type == SignalType.CLOSE:
            return self._close_position(signal.timestamp, signal.current_price)
        
        return None
    
    def update_price(self, price: float, timestamp: datetime) -> Dict:
        """
        Update current price and calculate P&L.
        
        Args:
            price: Current price for XAUUSD
            timestamp: Current timestamp
            
        Returns:
            Updated portfolio snapshot
        """
        # Update position P&L if open
        if self.current_position and self.current_position.status == TradeStatus.OPEN:
            pnl, pnl_pct = self._calculate_pnl(
                self.current_position.signal_type,
                self.current_position.entry_price,
                price,
                self.current_position.quantity
            )
            self.current_position.pnl = pnl
            self.current_position.pnl_pct = pnl_pct
        
        # Create snapshot
        snapshot = self._create_portfolio_snapshot(price)
        self.portfolio_snapshots.append(snapshot)
        
        return {
            "timestamp": timestamp.isoformat(),
            "price": price,
            "portfolio_value": snapshot.total_value,
            "pnl_total": snapshot.pnl_total,
            "position_pnl": self.current_position.pnl if self.current_position else 0.0,
        }
    
    # ========================================================================
    # PRIVATE METHODS
    # ========================================================================
    
    def _execute_trade(self, model_name: str, signal: ModelSignal) -> TradeExecution:
        """Execute a new trade."""
        # Calculate position size using Kelly criterion
        size = self._calculate_position_size(signal.confidence)
        
        # Create trade record
        trade = TradeExecution(
            model_name=model_name,
            signal_type=signal.signal_type,
            entry_price=signal.entry_price,
            quantity=size,
            position_value=size * signal.entry_price,
            status=TradeStatus.OPEN,
            regime=signal.regime,
            confidence=signal.confidence,
        )
        
        # Apply commission
        trade.commission = self._calculate_commission(trade.position_value)
        
        # Apply slippage
        trade.slippage = self._calculate_slippage(signal.entry_price)
        
        # Update portfolio
        if signal.signal_type == SignalType.LONG:
            self.position_sizes["XAUUSD"] = size
            self.portfolio.current_cash -= trade.position_value
        else:  # SHORT
            self.position_sizes["XAUUSD"] = -size
            self.portfolio.current_cash += trade.position_value
        
        # Track trade
        self.trades.append(trade)
        self.daily_trades.append(trade)
        self.current_position = trade
        
        logger.info(f"Trade executed: {trade.model_name} {trade.signal_type.value} {size:.2f} oz @ {signal.entry_price:.2f}")
        
        return trade
    
    def _close_position(self, timestamp: datetime, exit_price: float) -> Optional[TradeExecution]:
        """Close current open position."""
        if not self.current_position or self.current_position.status != TradeStatus.OPEN:
            return None
        
        trade = self.current_position
        trade.exit_price = exit_price
        trade.exit_time = timestamp
        
        # Calculate P&L
        pnl, pnl_pct = self._calculate_pnl(
            trade.signal_type,
            trade.entry_price,
            exit_price,
            trade.quantity
        )
        trade.pnl = pnl - trade.commission - trade.slippage
        trade.pnl_pct = (trade.pnl / trade.position_value) * 100 if trade.position_value > 0 else 0
        
        trade.status = TradeStatus.CLOSED
        
        # Update portfolio
        self.position_sizes["XAUUSD"] = 0
        if trade.signal_type == SignalType.LONG:
            self.portfolio.current_cash += trade.quantity * exit_price - trade.commission - trade.slippage
        else:
            self.portfolio.current_cash -= trade.quantity * exit_price + trade.commission + trade.slippage
        self.daily_pnl += trade.pnl
        
        logger.info(f"Position closed: P&L ${trade.pnl:.2f} ({trade.pnl_pct:.2f}%)")
        
        self.current_position = None
        return trade
    
    def _calculate_position_size(self, confidence: float) -> float:
        """Calculate position size using Kelly criterion."""
        # Estimate win probability from confidence
        win_prob = (confidence + 1.0) / 2.0  # Scale 0.5-1.0 based on confidence
        
        # Kelly fraction: f = (p * b - q) / b
        # Simplified for gold: assume 1:1 payoff
        kelly_fraction = win_prob - (1 - win_prob)
        
        # Apply Kelly fraction and config limit
        position_fraction = kelly_fraction * self.config.kelly_fraction
        position_fraction = min(position_fraction, self.config.max_position_pct)
        position_fraction = max(position_fraction, 0.01)  # Minimum position
        
        # Convert to ounces (assuming current price around $2000/oz, could be parameterized)
        position_value = self._create_portfolio_snapshot().total_value * position_fraction
        position_ounces = position_value / 2000.0  # Rough estimate
        
        return position_ounces
    
    def _calculate_commission(self, trade_value: float) -> float:
        """Calculate commission for trade."""
        return max(
            self.config.commission_per_trade,
            trade_value * self.config.commission_pct
        )
    
    def _calculate_slippage(self, price: float) -> float:
        """Calculate slippage for trade."""
        return price * (self.config.slippage_pct / 100.0)
    
    def _calculate_pnl(self, signal_type: SignalType, entry: float, exit: float, quantity: float) -> Tuple[float, float]:
        """Calculate P&L for a trade."""
        if signal_type == SignalType.LONG:
            pnl = (exit - entry) * quantity
        else:  # SHORT
            pnl = (entry - exit) * quantity
        
        pnl_pct = (pnl / (entry * quantity)) * 100 if entry > 0 else 0
        return pnl, pnl_pct
    
    def _check_risk_limits(self) -> bool:
        """Check if trading can continue based on risk limits."""
        total_equity = self._create_portfolio_snapshot().total_value
        
        # Check daily loss limit
        if self.daily_pnl < -total_equity * self.config.max_daily_loss_pct:
            logger.warning(f"Daily loss limit exceeded: ${self.daily_pnl:.2f}")
            return False
        
        # Check maximum drawdown
        portfolio_return = (total_equity - self.config.initial_capital) / self.config.initial_capital
        if portfolio_return < -self.config.max_drawdown_pct:
            logger.warning(f"Maximum drawdown exceeded: {portfolio_return*100:.2f}%")
            return False
        
        return True
    
    def _calculate_win_rate(self) -> float:
        """Calculate win rate from closed trades."""
        if not self.trades:
            return 0.0
        
        closed_trades = [t for t in self.trades if t.status == TradeStatus.CLOSED]
        if not closed_trades:
            return 0.0
        
        wins = len([t for t in closed_trades if t.pnl > 0])
        return wins / len(closed_trades)
    
    def _create_portfolio_snapshot(self, current_price: Optional[float] = None) -> PortfolioSnapshot:
        """Create a point-in-time portfolio snapshot."""
        if current_price is None:
            current_price = self.current_position.entry_price if self.current_position else 2000.0
        
        # Calculate position value
        position_quantity = self.position_sizes.get("XAUUSD", 0)
        position_value = position_quantity * current_price
        
        # Calculate P&L
        pnl_realized = sum(t.pnl for t in self.trades if t.status == TradeStatus.CLOSED)
        pnl_unrealized = sum(t.pnl for t in self.trades if t.status == TradeStatus.OPEN)
        pnl_total = pnl_realized + pnl_unrealized
        
        # Calculate metrics
        total_value = self.portfolio.current_cash + position_value
        return_pct = ((total_value - self.config.initial_capital) / self.config.initial_capital) * 100
        
        return PortfolioSnapshot(
            timestamp=datetime.now(),
            total_value=total_value,
            cash=self.portfolio.current_cash,
            position_quantity=position_quantity,
            position_value=position_value,
            pnl_realized=pnl_realized,
            pnl_unrealized=pnl_unrealized,
            pnl_total=pnl_total,
            daily_pnl=self.daily_pnl,
            return_pct=return_pct,
            sharpe_ratio=self._calculate_sharpe(),
            max_drawdown=self._calculate_max_drawdown(),
            win_rate=self._calculate_win_rate(),
            num_trades=len(self.trades),
        )
    
    def _calculate_sharpe(self, risk_free_rate: float = 0.02) -> float:
        """Calculate Sharpe ratio from portfolio snapshots."""
        if len(self.portfolio_snapshots) < 2:
            return 0.0
        
        returns = []
        for i in range(1, len(self.portfolio_snapshots)):
            prev = self.portfolio_snapshots[i-1]
            curr = self.portfolio_snapshots[i]
            ret = (curr.total_value - prev.total_value) / prev.total_value
            returns.append(ret)
        
        if not returns:
            return 0.0
        
        mean_return = np.mean(returns)
        std_return = np.std(returns)
        
        if std_return == 0:
            return 0.0
        
        return (mean_return - risk_free_rate / 252) / std_return * np.sqrt(252)
    
    def _calculate_max_drawdown(self) -> float:
        """Calculate maximum drawdown from portfolio values."""
        if not self.portfolio_snapshots:
            return 0.0
        
        equity_curve = [s.total_value for s in self.portfolio_snapshots]
        running_max = np.maximum.accumulate(equity_curve)
        drawdown = (np.array(equity_curve) - running_max) / running_max
        
        return float(np.min(drawdown)) * 100
    
    def get_total_pnl(self) -> float:
        """Get total realized P&L."""
        return sum(t.pnl for t in self.trades if t.status == TradeStatus.CLOSED)
    
    def get_trade_history(self, limit: int = 50) -> List[Dict]:
        """Get recent trade history."""
        trades = self.trades[-limit:]
        return [
            {
                "trade_id": t.trade_id,
                "model_name": t.model_name,
                "signal_type": t.signal_type.value,
                "entry_price": t.entry_price,
                "exit_price": t.exit_price,
                "quantity": t.quantity,
                "entry_time": t.entry_time.isoformat(),
                "exit_time": t.exit_time.isoformat() if t.exit_time else None,
                "pnl": t.pnl,
                "pnl_pct": t.pnl_pct,
                "status": t.status.value,
            }
            for t in trades
        ]
