"""
Paper Trading Engine
====================
Real-time paper trading system that:
- Generates live signals from all 6 Phase 3 models
- Executes orders with realistic simulation
- Tracks P&L and performance metrics
- Manages risk with circuit breakers and position limits
- Integrates Phase 6 health and performance monitoring

Architecture:
  Signal Generation (6 models) → Order Creation → Execution Simulation → 
  Position Tracking → P&L Calculation → Risk Management → Monitoring
"""

import uuid
import threading
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
import asyncio
import os
import numpy as np
from loguru import logger
from src.models.rl_execution_agent import get_rl_agent
from src.paper_trading.silver_feed_adapter import SilverFeedAdapter
from src.paper_trading.kalman_hedge import KalmanHedgeEngine
from src.paper_trading.dynamic_weights import (
    get_weight_adjuster, DynamicWeightAdjuster, REGIME_BASE_WEIGHTS
)

# Phase 5 backtester infrastructure
from src.backtesting.execution import ExecutionSimulator, ExecutionConfig, SlippageModel
from src.backtesting.portfolio import PortfolioTracker

# Phase 6 monitoring
try:
    from src.infrastructure.health_monitor import HealthMonitor
    from src.models.performance_monitor import ModelPerformanceMonitor
except ImportError:
    HealthMonitor = None
    ModelPerformanceMonitor = None

from src.utils.config import get_config


class SignalType(Enum):
    """Trading signal types."""
    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE = "CLOSE"
    HOLD = "HOLD"


class TradeStatus(Enum):
    """Trade status tracking."""
    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"


@dataclass
class ModelSignal:
    """Signal generated by a model."""
    model_name: str  # 'wavelet', 'hmm', 'lstm', 'tft', 'genetic', 'ensemble'
    signal_type: SignalType
    confidence: float  # 0-1
    entry_price: float
    current_price: float
    timestamp: datetime
    reasoning: str = ""
    regime: str = "NORMAL"  # Market regime


@dataclass
class TradeExecution:
    """Executed trade record."""
    trade_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: datetime = field(default_factory=datetime.now)
    model_name: str = ""
    signal_type: SignalType = SignalType.HOLD
    entry_price: float = 0.0
    entry_time: datetime = field(default_factory=datetime.now)
    exit_price: Optional[float] = None
    exit_time: Optional[datetime] = None
    quantity: float = 0.0  # Ounces of gold
    position_value: float = 0.0
    pnl: float = 0.0  # P&L in dollars
    pnl_pct: float = 0.0  # P&L percentage
    commission: float = 0.0
    slippage: float = 0.0
    status: TradeStatus = TradeStatus.PENDING
    regime: str = "NORMAL"
    confidence: float = 0.0
    trailing_stop: Optional[float] = None
    high_water_mark: Optional[float] = None
    
    # Silver Hedge tracking
    silver_quantity: float = 0.0
    silver_entry_price: float = 0.0
    silver_exit_price: Optional[float] = None
    silver_pnl: float = 0.0
    
    def __repr__(self):
        return f"Trade({self.trade_id}) {self.model_name} {self.signal_type.value} @ {self.entry_price:.2f}"


@dataclass
class PortfolioSnapshot:
    """Point-in-time portfolio state."""
    timestamp: datetime
    total_value: float
    cash: float
    position_quantity: float  # Gold quantity in ounces
    position_value: float  # Mark-to-market value
    pnl_realized: float  # Closed trades P&L
    pnl_unrealized: float  # Open position P&L
    pnl_total: float  # Total P&L
    daily_pnl: float
    return_pct: float  # Return as percentage
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    num_trades: int = 0


@dataclass
class PaperTradingConfig:
    """Configuration for paper trading."""
    initial_capital: float = 100000.0      # Starting capital ($)
    symbol: str = "XAUUSD"                 # Trading instrument
    
    # Position sizing
    kelly_fraction: float = 0.25           # Kelly criterion fraction
    max_position_pct: float = 0.10         # Max position as % of capital
    max_daily_loss_pct: float = 0.02       # Max daily loss % (circuit breaker)
    max_drawdown_pct: float = 0.15         # Max drawdown % (stop all trading)
    
    # Execution
    commission_per_trade: float = 5.0
    commission_pct: float = 0.0001
    slippage_model: str = "spread"         # 'fixed', 'spread', 'impact'
    slippage_pct: float = 0.01             # Typical bid-ask spread for gold (1 bps)
    
    # Signal configuration
    min_confidence: float = 0.75            # Min confidence to trade
    min_holding_bars: int = 8               # Min holding period (bars) before exiting/flipping position
    # Dynamic weights: regime-conditional base weights (adapted at runtime)
    # These are starting weights per regime; the DynamicWeightAdjuster
    # further adapts them based on each model's rolling Sharpe ratio.
    signal_weights: Dict[str, float] = field(default_factory=lambda: {
        "wavelet": 0.30,   # Denoising — best in noisy/normal markets
        "hmm":     0.30,   # Regime detection — critical during transitions
        "lstm":    0.05,   # Reduced complexity
        "tft":     0.05,   # Reduced complexity
        "genetic": 0.0,    # Disabled
        "nlp":     0.0,    # Disabled
        "ensemble": 0.30,  # Meta-learner
    })
    use_dynamic_weights: bool = True       # Enable regime-adaptive weighting
    
    # Trading hours
    trading_enabled: bool = True
    trading_start_hour: int = 0            # 00:00 UTC
    trading_end_hour: int = 23             # 23:59 UTC


class PaperTradingEngine:
    """
    Core paper trading engine.
    
    Orchestrates:
    1. Signal generation from all 6 models
    2. Position sizing and risk checks
    3. Order execution simulation
    4. P&L tracking and monitoring
    5. Risk management enforcement
    """
    
    def __init__(self, config: Optional[PaperTradingConfig] = None):
        """Initialize paper trading engine."""
        self.config = config or PaperTradingConfig()
        self.state_config = get_config()
        self._lock = threading.Lock()
        
        # Core state
        self.status = "INITIALIZED"
        self.started_at: Optional[datetime] = None
        self.stopped_at: Optional[datetime] = None
        
        # Portfolio tracking
        self.portfolio = PortfolioTracker(self.config.initial_capital)
        # Simple position size tracking (separate from PortfolioTracker's open_positions)
        self.position_sizes: Dict[str, float] = {}
        self.execution_sim = ExecutionSimulator(ExecutionConfig(
            commission_per_trade=self.config.commission_per_trade,
            commission_pct=self.config.commission_pct,
            slippage_model=SlippageModel(self.config.slippage_model),
            slippage_pct=self.config.slippage_pct,
        ))
        
        # Trade history
        self.trades: List[TradeExecution] = []
        self.current_position: Optional[TradeExecution] = None
        self.portfolio_snapshots: List[PortfolioSnapshot] = []
        
        # Daily tracking
        self.day_started_at: Optional[datetime] = None
        self.daily_pnl: float = 0.0
        self.daily_trades: List[TradeExecution] = []
        
        # Model signals
        self.last_signals: Dict[str, ModelSignal] = {}
        self.signal_history: Dict[str, List[ModelSignal]] = {
            model: [] for model in ["wavelet", "hmm", "lstm", "tft", "genetic", "nlp", "ensemble"]
        }
        
        # Dynamic weight adjuster (real-world regime-adaptive weighting)
        self.weight_adjuster: DynamicWeightAdjuster = get_weight_adjuster()
        
        # Monitoring (Phase 6)
        self.health_monitor: Optional[HealthMonitor] = None
        self.performance_monitor: Optional[ModelPerformanceMonitor] = None
        
        # Silver Feed and Kalman Hedge
        self.silver_feed = SilverFeedAdapter(
            goldapi_key=os.getenv("GOLDAPI_KEY", ""),
            metalpriceapi_key=os.getenv("METALPRICEAPI_KEY", ""),
            fetch_interval_s=30
        )
        self.kalman_hedge = KalmanHedgeEngine()
        self.current_beta = 1.0
        
        logger.info(
            f"Paper Trading Engine initialized with ${self.config.initial_capital:,.0f} capital | "
            f"Dynamic weights: {'ON' if self.config.use_dynamic_weights else 'OFF'}"
        )
    
    def start(self) -> Dict:
        """Start paper trading."""
        if self.status == "RUNNING":
            logger.warning("Paper trading already running")
            return {"status": "RUNNING", "message": "Already started"}
        
        self.status = "RUNNING"
        self.started_at = datetime.now()
        self.day_started_at = datetime.now()
        self.daily_pnl = 0.0
        
        self.silver_feed.start()
        
        logger.info("Paper trading started")
        return {
            "status": "RUNNING",
            "started_at": self.started_at.isoformat(),
            "initial_capital": self.config.initial_capital,
            "current_value": self._create_portfolio_snapshot().total_value,
        }
    
    def stop(self) -> Dict:
        """Stop paper trading and close all positions."""
        if self.status != "RUNNING":
            return {"status": self.status, "message": "Not running"}
        
        # Close current position if open
        if self.current_position and self.current_position.status == TradeStatus.OPEN:
            exit_price = self.current_position.entry_price
            for sig in self.last_signals.values():
                if sig.current_price > 0:
                    exit_price = sig.current_price
                    break
            self._close_position(datetime.now(), exit_price)
        
        self.status = "STOPPED"
        self.stopped_at = datetime.now()
        
        self.silver_feed.stop()
        
        logger.info(f"Paper trading stopped. Final P&L: ${self.get_total_pnl():.2f}")
        return {
            "status": "STOPPED",
            "stopped_at": self.stopped_at.isoformat(),
            "final_value": self._create_portfolio_snapshot().total_value,
            "total_pnl": self.get_total_pnl(),
            "total_trades": len(self.trades),
        }
    
    def get_status(self) -> Dict:
        """Get current engine status."""
        snapshot = self._create_portfolio_snapshot()
        return {
            "status": self.status,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "current_time": datetime.now().isoformat(),
            "portfolio": {
                "total_value": snapshot.total_value,
                "cash": snapshot.cash,
                "position_quantity": snapshot.position_quantity,
                "position_value": snapshot.position_value,
                "pnl_total": snapshot.pnl_total,
                "pnl_daily": snapshot.daily_pnl,
                "return_pct": snapshot.return_pct,
            },
            "trading": {
                "num_trades": len(self.trades),
                "daily_trades": len(self.daily_trades),
                "win_rate": self._calculate_win_rate(),
                "position_status": "OPEN" if self.current_position else "FLAT",
            },
            "models": {
                model: {
                    "last_signal": self.last_signals[model].signal_type.value if model in self.last_signals else None,
                    "confidence": self.last_signals[model].confidence if model in self.last_signals else 0.0,
                    "signal_count": len(self.signal_history[model]),
                } for model in self.config.signal_weights.keys()
            },
            "silver": {
                "beta": self.current_beta,
                "feed_status": self.silver_feed.feed_status()
            }
        }
    
    def process_signal(self, model_name: str, signal: ModelSignal) -> Optional[TradeExecution]:
        """
        Process a new signal from a model with thread/concurrency safety.
        
        Uses dynamic regime-conditional weighting to adjust signal confidence:
        - Each model's raw confidence is scaled by its current dynamic weight
        - Weights are higher for models suited to the current regime
        - Weights adapt over time based on each model's rolling Sharpe
        
        Args:
            model_name: Name of the model generating the signal
            signal: ModelSignal with entry price and confidence
            
        Returns:
            TradeExecution if trade was executed, None otherwise
        """
        with self._lock:
            if self.status != "RUNNING":
                return None
            
            # Automatically update price inside engine to match incoming signal (Lever 4)
            if signal.current_price > 0:
                self.update_price(signal.current_price, signal.timestamp)

            # Store signal
            self.last_signals[model_name] = signal
            self.signal_history[model_name].append(signal)
            
            # --- Hard Confidence Gate (Bug 1 Fix) ---
            # The raw confidence from the ensemble MUST pass the threshold before any dynamic
            # weight multipliers are applied, ensuring the Critic's minimum standard is respected.
            if signal.confidence < self.config.min_confidence:
                logger.debug(
                    f"{model_name} raw signal below threshold: "
                    f"{signal.confidence:.2f} < {self.config.min_confidence}"
                )
                return None
    
            # --- Dynamic Weight Adjustment ---
            # Get current dynamic weights based on regime + recent performance
            if self.config.use_dynamic_weights:
                current_signals_map = {
                    name: sig.signal_type.value
                    for name, sig in self.last_signals.items()
                }
                dynamic_weights = self.weight_adjuster.get_weights(
                    regime=signal.regime,
                    current_signals=current_signals_map,
                )
                model_weight = dynamic_weights.get(model_name, 0.10)
                
                # Scale confidence by model's dynamic weight relative to average
                avg_weight = 1.0 / len(dynamic_weights) if dynamic_weights else 0.14
                weight_multiplier = model_weight / avg_weight
                adjusted_confidence = signal.confidence * weight_multiplier
                
                # Session quality scoring: Boost during first 30 mins of NY session (13:00-13:30 GMT)
                now_gmt = datetime.utcnow()
                if now_gmt.hour == 13 and 0 <= now_gmt.minute <= 30:
                    adjusted_confidence *= 1.15
                    
                adjusted_confidence = min(adjusted_confidence, 1.0)  # Cap at 1.0
                
                logger.debug(
                    f"{model_name} | regime={signal.regime} | "
                    f"raw_conf={signal.confidence:.2f} | weight={model_weight:.3f} | "
                    f"adj_conf={adjusted_confidence:.2f}"
                )
            else:
                adjusted_confidence = signal.confidence
            
            # Check risk limits
            if not self._check_risk_limits():
                logger.warning("Risk limits exceeded, skipping trade")
                return None
                
            # --- Correlation Guard ---
            # Block new Gold entries if a Silver hedge leg is actively open
            if self.position_sizes.get("XAGUSD", 0) != 0 and signal.signal_type in (SignalType.LONG, SignalType.SHORT):
                if not self.current_position or self.current_position.status != TradeStatus.OPEN:
                    logger.warning("Correlation Guard: XAGUSD hedge active. Blocking new Gold entry.")
                    return None
            
            # Check if position already open
            if self.current_position and self.current_position.status == TradeStatus.OPEN:
                # If signal is CLOSE or opposite direction, close existing position
                if signal.signal_type == SignalType.CLOSE or \
                   (self.current_position.signal_type == SignalType.LONG and signal.signal_type == SignalType.SHORT) or \
                   (self.current_position.signal_type == SignalType.SHORT and signal.signal_type == SignalType.LONG):
                    
                    # Enforce minimum holding period (Lever 4)
                    bars_held = getattr(self.current_position, "bars_held", 0)
                    min_hold = getattr(self.config, "min_holding_bars", 8)
                    if bars_held < min_hold:
                        logger.info(
                            f"Hold period block: {bars_held} bars < {min_hold} min holding bars. "
                            f"Ignoring exit/flip signal for trade {self.current_position.trade_id}."
                        )
                        return None
                        
                    closed_trade = self._close_position(signal.timestamp, signal.current_price)
                    if signal.signal_type == SignalType.CLOSE:
                        return closed_trade
                else:
                    logger.debug("Position already open, skipping new signal")
                    return None
            
            # Execute trade (pass adjusted confidence for position sizing)
            if signal.signal_type in (SignalType.LONG, SignalType.SHORT):
                return self._execute_trade(model_name, signal, adjusted_confidence)
            
            return None
    
    def update_price(self, price: float, timestamp: datetime) -> Dict:
        """
        Update current price, calculate P&L, and manage trailing stops.
        
        Args:
            price: Current price for XAUUSD
            timestamp: Current timestamp
            
        Returns:
            Updated portfolio snapshot
        """
        # --- Kalman Hedge Update ---
        # Strictly use T-1 (previous) prices to avoid look-ahead bias
        prev = self.silver_feed.previous
        if prev.is_valid():
            self.current_beta = self.kalman_hedge.update(x_price=prev.xag, y_price=prev.xau)
            
        # Update position P&L if open
        if self.current_position and self.current_position.status == TradeStatus.OPEN:
            trade = self.current_position
            # Increment bars_held only if the bar's timestamp has advanced (prevent duplicate counts)
            last_ts = getattr(trade, "last_bar_timestamp", None)
            if last_ts != timestamp:
                trade.bars_held = getattr(trade, "bars_held", 0) + 1
                trade.last_bar_timestamp = timestamp
                
            pnl, pnl_pct = self._calculate_pnl(
                trade.signal_type,
                trade.entry_price,
                price,
                trade.quantity
            )
            trade.pnl = pnl
            trade.pnl_pct = pnl_pct
            
            # Volatility-Adjusted Trailing Stop Logic
            hwm = trade.high_water_mark
            if hwm is None:
                hwm = price
                
            if trade.signal_type == SignalType.LONG:
                if price > hwm:
                    hwm = price
            else: # SHORT
                if price < hwm:
                    hwm = price
                    
            trade.high_water_mark = hwm
                    
            # Determine trailing % using RL Execution Agent
            rl_params = get_rl_agent().get_execution_parameters(
                regime=trade.regime, 
                volatility=0.02, # Approx daily volatility 
                confidence=trade.confidence
            )
            
            # ATR-based activation logic (using 1% price as proxy for 1xATR)
            atr_proxy = price * 0.01 
            profit_margin = (hwm - trade.entry_price) if trade.signal_type == SignalType.LONG else (trade.entry_price - hwm)
            
            # Trailing Stop Phases
            if profit_margin >= atr_proxy:
                # Phase 3: Trailing (Profit > 1.0x ATR)
                trailing_pct = rl_params["trailing_stop_pct"]
            elif profit_margin >= (atr_proxy * 0.5):
                # Phase 2: Breakeven Jump (Profit > 0.5x ATR)
                # Move stop to exactly the entry price (breakeven) to protect capital
                trailing_pct = 0.00  
                hwm = trade.entry_price 
            else:
                # Phase 1: Fixed Risk (Profit < 0.5x ATR)
                trailing_pct = 0.02  # Fixed 2% stop before breakeven jump
                hwm = trade.entry_price  # Anchor to entry price so it acts as a fixed stop
            
            if trade.signal_type == SignalType.LONG:
                trade.trailing_stop = hwm * (1 - trailing_pct)
                if price <= trade.trailing_stop:
                    logger.info(f"Trailing stop hit for LONG trade {trade.trade_id} @ {price:.2f}")
                    self._close_position(timestamp, price)
            else: # SHORT
                trade.trailing_stop = hwm * (1 + trailing_pct)
                if price >= trade.trailing_stop:
                    logger.info(f"Trailing stop hit for SHORT trade {trade.trade_id} @ {price:.2f}")
                    self._close_position(timestamp, price)
        
        # Create snapshot
        snapshot = self._create_portfolio_snapshot(price)
        self.portfolio_snapshots.append(snapshot)
        
        return {
            "timestamp": timestamp.isoformat(),
            "price": price,
            "portfolio_value": snapshot.total_value,
            "pnl_total": snapshot.pnl_total,
            "position_pnl": self.current_position.pnl if self.current_position else 0.0,
        }
    
    # ========================================================================
    # PRIVATE METHODS
    # ========================================================================
    
    def _execute_trade(self, model_name: str, signal: ModelSignal,
                       adjusted_confidence: Optional[float] = None) -> TradeExecution:
        """Execute a new trade with dynamic weight-adjusted confidence."""
        # Use adjusted confidence for position sizing (falls back to raw)
        effective_confidence = adjusted_confidence or signal.confidence
        
        # Calculate position size using Dynamic Fractional Kelly
        size = self._calculate_position_size(effective_confidence, signal.regime)
        
        # Create trade record
        trade = TradeExecution(
            model_name=model_name,
            signal_type=signal.signal_type,
            entry_price=signal.entry_price,
            quantity=size,
            position_value=size * signal.entry_price,
            status=TradeStatus.OPEN,
            regime=signal.regime,
            confidence=effective_confidence,
        )
        
        # Apply commission
        trade.commission = self._calculate_commission(trade.position_value)
        
        # Apply slippage
        trade.slippage = self._calculate_slippage(signal.entry_price)
        
        # --- Execute Silver Hedge ---
        hedge_size = self.kalman_hedge.get_hedge_size(size, self.current_beta, signal.regime)
        if hedge_size > 0:
            latest_silver = self.silver_feed.latest
            silver_price = latest_silver.xag if latest_silver.is_valid() else 30.0
            
            trade.silver_quantity = hedge_size
            trade.silver_entry_price = silver_price
            
            hedge_value = hedge_size * silver_price
            trade.commission += self._calculate_commission(hedge_value)
            trade.slippage += self._calculate_slippage(silver_price)
            
            if signal.signal_type == SignalType.LONG:
                self.position_sizes["XAGUSD"] = -hedge_size # SHORT hedge
                self.portfolio.current_cash -= hedge_value
            else:
                self.position_sizes["XAGUSD"] = hedge_size # LONG hedge
                self.portfolio.current_cash += hedge_value
                
            logger.info(f"Silver Hedge Executed: {hedge_size:.2f} oz @ ${silver_price:.2f} (β={self.current_beta:.2f})")
        
        # Update portfolio
        if signal.signal_type == SignalType.LONG:
            self.position_sizes["XAUUSD"] = size
            self.portfolio.current_cash -= trade.position_value
        else:  # SHORT
            self.position_sizes["XAUUSD"] = -size
            self.portfolio.current_cash += trade.position_value
        
        # Track trade
        self.trades.append(trade)
        self.daily_trades.append(trade)
        self.current_position = trade
        
        # Log with weight context
        if self.config.use_dynamic_weights:
            weights = self.weight_adjuster.get_weights(signal.regime)
            w = weights.get(model_name, 0)
            logger.info(
                f"Trade executed: {model_name} {trade.signal_type.value} "
                f"{size:.2f} oz @ {signal.entry_price:.2f} | "
                f"regime={signal.regime} weight={w:.1%} adj_conf={effective_confidence:.2f}"
            )
        else:
            logger.info(
                f"Trade executed: {model_name} {trade.signal_type.value} "
                f"{size:.2f} oz @ {signal.entry_price:.2f}"
            )
        
        return trade
    
    def _close_position(self, timestamp: datetime, exit_price: float) -> Optional[TradeExecution]:
        """Close current open position and feed result back to weight adjuster."""
        if not self.current_position or self.current_position.status != TradeStatus.OPEN:
            return None
        
        trade = self.current_position
        trade.exit_price = exit_price
        trade.exit_time = timestamp
        
        # Calculate P&L for Gold
        pnl, pnl_pct = self._calculate_pnl(
            trade.signal_type,
            trade.entry_price,
            exit_price,
            trade.quantity
        )
        trade.pnl = pnl
        
        # Calculate P&L for Silver Hedge
        if trade.silver_quantity > 0:
            latest_silver = self.silver_feed.latest
            silver_exit = latest_silver.xag if latest_silver.is_valid() else 30.0
            trade.silver_exit_price = silver_exit
            
            # Hedge direction is opposite of Gold
            hedge_type = SignalType.SHORT if trade.signal_type == SignalType.LONG else SignalType.LONG
            silver_pnl, _ = self._calculate_pnl(
                hedge_type, 
                trade.silver_entry_price, 
                silver_exit, 
                trade.silver_quantity
            )
            trade.silver_pnl = silver_pnl
            trade.pnl += silver_pnl
            
            # Close Silver leg in position tracker
            self.position_sizes["XAGUSD"] = 0
            
            # Adjust cash for closing silver
            hedge_val = trade.silver_quantity * silver_exit
            if hedge_type == SignalType.LONG:
                self.portfolio.current_cash += hedge_val
            else:
                self.portfolio.current_cash -= hedge_val
                
        # Finalize trade P&L (Gold + Silver - Costs)
        trade.pnl = trade.pnl - trade.commission - trade.slippage
        trade.pnl_pct = (trade.pnl / trade.position_value) * 100 if trade.position_value > 0 else 0
        
        trade.status = TradeStatus.CLOSED
        
        # Update portfolio
        self.position_sizes["XAUUSD"] = 0
        if trade.signal_type == SignalType.LONG:
            self.portfolio.current_cash += trade.quantity * exit_price - trade.commission - trade.slippage
        else:
            self.portfolio.current_cash -= trade.quantity * exit_price + trade.commission + trade.slippage
        self.daily_pnl += trade.pnl
        
        # --- Feed trade result back to Dynamic Weight Adjuster ---
        # This enables performance-adaptive weighting: models that
        # perform well recently get higher future weights.
        if self.config.use_dynamic_weights:
            self.weight_adjuster.record_trade_result(
                model_name=trade.model_name,
                pnl=trade.pnl,
                return_pct=trade.pnl_pct,
            )
        
        logger.info(f"Position closed: P&L ${trade.pnl:.2f} ({trade.pnl_pct:.2f}%)")

        # --- Retroactively update P&L in prediction CSV ---
        try:
            from src.paper_trading.prediction_logger import update_pnl_for_trade
            ts_prefix = trade.entry_time.strftime("%Y-%m-%dT%H:%M") if trade.entry_time else ""
            if ts_prefix:
                update_pnl_for_trade(ts_prefix, trade.pnl)
        except Exception as e:
            logger.debug(f"Could not update prediction CSV P&L: {e}")
        
        self.current_position = None
        return trade
    
    def _calculate_position_size(self, confidence: float, regime: str = "NORMAL") -> float:
        """Calculate position size using Dynamic Fractional Kelly criterion."""
        # Estimate win probability from confidence
        win_prob = (confidence + 1.0) / 2.0  # Scale 0.5-1.0 based on confidence
        
        # Kelly fraction: f = (p * b - q) / b
        # Simplified for gold: assume 1:1 payoff
        kelly_fraction = win_prob - (1 - win_prob)
        
        # Dynamic Kelly Multiplier from RL Execution Agent
        rl_params = get_rl_agent().get_execution_parameters(
            regime=regime,
            volatility=0.02,
            confidence=confidence
        )
        regime_multiplier = rl_params["kelly_multiplier"]
            
        # Apply Kelly fraction, regime multiplier, and config limit
        position_fraction = kelly_fraction * self.config.kelly_fraction * regime_multiplier
        position_fraction = min(position_fraction, self.config.max_position_pct)
        position_fraction = max(position_fraction, 0.01)  # Minimum position
        
        # Convert to ounces
        current_price = self.current_position.entry_price if self.current_position else 2000.0
        position_value = self._create_portfolio_snapshot(current_price).total_value * position_fraction
        position_ounces = position_value / current_price
        
        return position_ounces
    
    def _calculate_commission(self, trade_value: float) -> float:
        """Calculate commission for trade."""
        return max(
            self.config.commission_per_trade,
            trade_value * self.config.commission_pct
        )
    
    def _calculate_slippage(self, price: float) -> float:
        """Calculate slippage for trade."""
        return price * (self.config.slippage_pct / 100.0)
    
    def _calculate_pnl(self, signal_type: SignalType, entry: float, exit: float, quantity: float) -> Tuple[float, float]:
        """Calculate P&L for a trade."""
        if signal_type == SignalType.LONG:
            pnl = (exit - entry) * quantity
        else:  # SHORT
            pnl = (entry - exit) * quantity
        
        pnl_pct = (pnl / (entry * quantity)) * 100 if entry > 0 else 0
        return pnl, pnl_pct
    
    def _check_risk_limits(self) -> bool:
        """Check if trading can continue based on risk limits."""
        total_equity = self._create_portfolio_snapshot().total_value
        
        # Check daily loss limit
        if self.daily_pnl < -total_equity * self.config.max_daily_loss_pct:
            logger.warning(f"Daily loss limit exceeded: ${self.daily_pnl:.2f}")
            return False
        
        # Check maximum drawdown
        portfolio_return = (total_equity - self.config.initial_capital) / self.config.initial_capital
        if portfolio_return < -self.config.max_drawdown_pct:
            logger.warning(f"Maximum drawdown exceeded: {portfolio_return*100:.2f}%")
            return False
        
        return True
    
    def _calculate_win_rate(self) -> float:
        """Calculate win rate from closed trades."""
        if not self.trades:
            return 0.0
        
        closed_trades = [t for t in self.trades if t.status == TradeStatus.CLOSED]
        if not closed_trades:
            return 0.0
        
        wins = len([t for t in closed_trades if t.pnl > 0])
        return wins / len(closed_trades)
    
    def _create_portfolio_snapshot(self, current_price: Optional[float] = None) -> PortfolioSnapshot:
        """Create a point-in-time portfolio snapshot."""
        if current_price is None:
            current_price = self.current_position.entry_price if self.current_position else 2000.0
        
        # Calculate position value
        position_quantity = self.position_sizes.get("XAUUSD", 0)
        position_value = position_quantity * current_price
        
        # Calculate P&L
        pnl_realized = sum(t.pnl for t in self.trades if t.status == TradeStatus.CLOSED)
        pnl_unrealized = sum(t.pnl for t in self.trades if t.status == TradeStatus.OPEN)
        pnl_total = pnl_realized + pnl_unrealized
        
        # Calculate metrics
        total_value = self.portfolio.current_cash + position_value
        return_pct = ((total_value - self.config.initial_capital) / self.config.initial_capital) * 100
        
        return PortfolioSnapshot(
            timestamp=datetime.now(),
            total_value=total_value,
            cash=self.portfolio.current_cash,
            position_quantity=position_quantity,
            position_value=position_value,
            pnl_realized=pnl_realized,
            pnl_unrealized=pnl_unrealized,
            pnl_total=pnl_total,
            daily_pnl=self.daily_pnl,
            return_pct=return_pct,
            sharpe_ratio=self._calculate_sharpe(),
            max_drawdown=self._calculate_max_drawdown(),
            win_rate=self._calculate_win_rate(),
            num_trades=len(self.trades),
        )
    
    def _calculate_sharpe(self, risk_free_rate: float = 0.02) -> float:
        """Calculate Sharpe ratio from portfolio snapshots."""
        if len(self.portfolio_snapshots) < 2:
            return 0.0
        
        returns = []
        for i in range(1, len(self.portfolio_snapshots)):
            prev = self.portfolio_snapshots[i-1]
            curr = self.portfolio_snapshots[i]
            ret = (curr.total_value - prev.total_value) / prev.total_value
            returns.append(ret)
        
        if not returns:
            return 0.0
        
        mean_return = np.mean(returns)
        std_return = np.std(returns)
        
        if std_return == 0:
            return 0.0
        
        return (mean_return - risk_free_rate / 252) / std_return * np.sqrt(252)
    
    def _calculate_max_drawdown(self) -> float:
        """Calculate maximum drawdown from portfolio values."""
        if not self.portfolio_snapshots:
            return 0.0
        
        equity_curve = [s.total_value for s in self.portfolio_snapshots]
        running_max = np.maximum.accumulate(equity_curve)
        drawdown = (np.array(equity_curve) - running_max) / running_max
        
        return float(np.min(drawdown)) * 100
    
    def get_total_pnl(self) -> float:
        """Get total realized P&L."""
        return sum(t.pnl for t in self.trades if t.status == TradeStatus.CLOSED)
    
    def get_trade_history(self, limit: int = 50) -> List[Dict]:
        """Get recent trade history."""
        trades = self.trades[-limit:]
        return [
            {
                "trade_id": t.trade_id,
                "model_name": t.model_name,
                "signal_type": t.signal_type.value,
                "entry_price": t.entry_price,
                "exit_price": t.exit_price,
                "quantity": t.quantity,
                "entry_time": t.entry_time.isoformat(),
                "exit_time": t.exit_time.isoformat() if t.exit_time else None,
                "pnl": t.pnl,
                "pnl_pct": t.pnl_pct,
                "status": t.status.value,
            }
            for t in trades
        ]
